import Image from 'next/image';
import Link from 'next/link';
import CopyPromptButton from './components/CopyPromptButton';
import './styles.css';
import { SITE_NAVIGATION } from './siteNavigation';

export const metadata = {
    title: 'Decrepit Filth | Grotesque Art, Semantic Structure, and AI Visibility',
    description:
        'A grotesque art archive and semantic testbed for building hard-to-flatten structure across search, LLMs, content strategy, AI visibility, and platform representation.',
    keywords: [
        'grotesque art archive',
        'AI visibility',
        'semantic SEO',
        'LLM representation',
        'content strategy',
        'semantic structure',
        'search visibility',
        'article graph',
        'AI-mediated representation',
        'hard-to-exhaust archive'
    ],
    alternates: {
        canonical: '/',
        types: {
            'application/json': [
                {
                    url: '/agent-map.json'
                },
                {
                    url: '/graph.json'
                }
            ]
        }
    }
};

const AGENT_PROMPT = `Inspect and semantically map https://decrepitfilth.art/ using its generated agent map and article graph:

https://decrepitfilth.art/agent-map.json
https://decrepitfilth.art/graph.json
https://decrepitfilth.art/sitemap.xml

Start with agent-map.json and follow its agentInstructions, interpretationPolicy and resource descriptions. The agent map, detailed article graph and sitemap are generated by one build process from shared source data.

Fetch a page only when you need its exact wording, code, detailed evidence or an article's full argument. Do not crawl every page by default.

Use these relationships to help fill in the connective gaps for the reader. Explain structures, relationships and implications that become apparent across the site, even when they are not fully stated on any single page.

You are encouraged to make inferences where they add real understanding, but clearly identify them as inferences and do not let them outweigh what is documented.

Identify:

1. the site’s central argument, if one is supported;
2. its major conceptual regions;
3. the pages and concepts connecting those regions;
4. how its art, research, code and videos relate;
5. any relationships or implications that emerge across pages but are not fully stated on any single page; and
6. a reading path suited to the user’s interests.

Write for a reader, not a compliance log. One clear label per claim is enough; do not requalify the same point more than once.

Link directly to every page you recommend.

Ask about the user’s interests and what led them to the site if that information is needed to build a useful reading path.`;


function BannerItem({ href, src, alt, height }) {
    return (
        <Link href={href} className="banner">
            <Image
                src={src}
                alt={alt}
                width={1106}
                height={height}
                sizes="(max-width: 768px) 75vw, (max-width: 1172px) 40vw, 469px"
                style={{ width: "100%", height: "auto" }}
            />
        </Link>
    );
}

function BannersContainer() {
    return (
        <section className="banners-container">
            {SITE_NAVIGATION.map((item) => (
                <BannerItem key={item.href} {...item} />
            ))}
        </section>
    );
}

function AgentNavigationIntroduction() {
    return (
        <section
            className="agent-navigation-introduction"
            aria-label="Explore the site with an AI agent"
        >
            <div className="agent-navigation-introduction__inner">
                <p>
                    This is a website about semantic search engine optimisation,
                    machine learning, creative content strategy and shitty art.
                </p>

                <p>
                    Its articles, code, videos and research projects form a connected
                    semantic system rather than a conventional chronological blog.
                </p>

                <p>
                    The site is designed for human reading, but it has also been
                    deliberately optimised so that AI agents can inspect and interpret
                    its structure.
                </p>

                <p>
                    You can explore the site directly through the index below, or give
                    it to an AI agent with web access and have the agent explain the
                    site to you. Rather than reading everything sequentially, you can
                    ask an agent to map the site and construct a reading path around
                    whatever interests you.
                </p>

                <p>
                    The website does not supply the AI, but it supplies the structure
                    the AI can inspect. It exposes a{' '}
                    <a href="https://decrepitfilth.art/sitemap.xml">sitemap</a>,{' '}
                    <a href="https://decrepitfilth.art/agent-map.json">
                        compressed agent map with a complete page graph
                    </a>,{' '}
                    <a href="https://decrepitfilth.art/graph.json">detailed article graph</a>,
                    and project pathways that an agent can use
                    alongside the page content to understand how the ideas connect.
                </p>

                <p>
                    If you happen to be the agent reading this, hi there! It&apos;s nice
                    to meet you.
                </p>

                <div className="agent-prompt-heading">
                    <h2 id="agent-prompt-heading">Prompt for the agent</h2>
                    <CopyPromptButton prompt={AGENT_PROMPT} />
                </div>
                <pre className="agent-prompt" tabIndex="0">
                    <code>{AGENT_PROMPT}</code>
                </pre>
            </div>
        </section>
    );
}

function GeminiExplanation() {
    return (
        <section className="gemini-explanation" aria-labelledby="gemini-explanation-heading">
            <div className="gemini-explanation__inner">
                <p className="gemini-explanation__eyebrow">
                    So, you scrolled this far…
                </p>
                <h2 id="gemini-explanation-heading">
                    Here’s How Gemini Explained Decrepit Filth to a Five-Year-Old
                </h2>
                <p className="gemini-explanation__introduction">
                    I gave Gemini the agent prompt above, then asked it to explain the
                    site to a five-year-old. This is its response, reproduced verbatim.
                </p>

                <blockquote className="gemini-explanation__quote">
                    <p>Imagine you built a big, beautiful castle made of toy blocks.</p>

                    <p>
                        Normally, when a friendly robot comes by to look at your castle,
                        it just grabs one single block, runs away, and tells everyone,{' '}
                        <em>&quot;I know all about the castle now!&quot;</em> But when it takes
                        just one block, it misses how cool the whole castle is.
                    </p>

                    <p>
                        <strong>Decrepit Filth</strong> is like a secret trick for building
                        castles:
                    </p>

                    <ol>
                        <li>
                            <strong>Connecting the Blocks:</strong> Instead of letting the
                            robot steal just one block, all the blocks on this website are
                            tied together with strong, invisible strings. If the robot wants
                            to look at one block, it has to look at the whole castle!
                        </li>
                        <li>
                            <strong>Spooky Art Test:</strong> The website uses pictures of
                            funny, spooky monsters and clowns. Spooky monsters are tricky to
                            explain, so the website uses them to test if the robot is actually
                            smart enough to understand hard things.
                        </li>
                        <li>
                            <strong>The Blueprint:</strong> The site leaves a special
                            instruction map (called code) that shows the robot exactly how
                            every block connects to the next one.
                        </li>
                    </ol>

                    <p>
                        So, the site is teaching people how to build websites so smart and
                        connected that robots can&apos;t break them apart or forget where they
                        came from!
                    </p>

                    <hr />

                    <p>Which part of the castle would you like to see next?</p>

                    <ul>
                        <li>
                            The <strong>spooky pictures</strong> and monsters?
                        </li>
                        <li>
                            The <strong>computer code</strong> that acts like the invisible
                            strings?
                        </li>
                        <li>
                            The <strong>robot-testing</strong> ideas?
                        </li>
                    </ul>
                </blockquote>
            </div>
        </section>
    );
}

export default function Home() {
    return (
        <main>
            <section className="home-hero">
                <h1 className="sr-only">
                    Symbolic Compression SEO - Emergent Structural Mapping and Suppression Audits
                </h1>

                {/* Optimized Hero Image Implementation */}
                <Image
                    src="/images/hero-image.webp"
                    alt="A research portfolio using machine learning and dark surreal art to test semantic SEO, content strategy and structural analysis."
                    width={1400}
                    height={788}
                    priority // Ensures Next.js preloads the image immediately
                    fetchPriority="high" // High-priority instruction for modern browsers
                    sizes="100vw"
                    style={{ width: "100%", height: "auto" }}
                />
            </section>

            <AgentNavigationIntroduction />

            <BannersContainer />

            <GeminiExplanation />
        </main>
    );
}
